### PR TITLE
updated name of python-catkin_pkg

### PR DESCRIPTION
**Pull request by jwhendy**
I couldn't build this due to a failure to resolve the dependency `python-catkin-pkg` which I believe should be `python-catkin_pkg`.

### CODE REVIEW

**Review by acxz — APPROVED** [review]
Nice to see you around @jwhendy !

**Comment by acxz** [comment]
Thx for the PR

**Comment by jwhendy** [comment]
@acxz Ha! Indeed :) As you probably figured, I haven't been much of a ROS user in a while... I had some build woes trying to get melodic happy again, and it looked like arch went in on noetic (inferring due to all the orphaned melodic packages?), so it was a good opportunity to try it out!

**Comment by acxz** [comment]
Yeah, I think that keeping up with back porting patches for melodic was just taxing. That or bionade finished his current project he was working with melodic on haha. Noetic has been working for me a good bit when I first created the packages, although I haven't used it in quite some time, (need to use ubuntu18 for a project requiring me to run ROS in a container). AchmadFathoni has been helping out quite a bit since I wasn't active at all last year.

Also just looking for some free time to get ROS2 packages in the AUR, but I won't really get that time till next year.

Hope you find the packages in good condition and if not send them PRs over haha!

**Comment by jwhendy** [comment]
Indeed, the boost mess alone was brutal (and I was only involved as that started coming up more and more, not with the workaround 1.69 pkg). I'm certainly willing to report/fix whatever I can! ros-noetic-ros-base finished building about 30min ago and went great!

**Pull request merged**
